const GENRES = [
  { id: 'strategy', label: 'Стратегії' },
  { id: 'family', label: 'Сімейні' },
  { id: 'party', label: 'Вечіркові' },
  { id: 'coop', label: 'Кооперативні' },
  { id: 'duel', label: 'Дуельні' },
  { id: 'abstract', label: 'Абстрактні' },
  { id: 'kids', label: 'Дитячі' },
];

const BADGES = {
  hit: { label: 'Хіт продажів', className: 'text-bg-warning' },
  new: { label: 'Новинка', className: 'text-bg-primary' },
  sale: { label: 'Знижка', className: 'text-bg-danger' },
};

const GAMES = [
  {
    id: 'carcassonne',
    title: 'Каркассон',
    genre: 'family',
    players: [2, 5],
    time: 40,
    age: 7,
    rating: 4.7,
    reviews: 318,
    price: 1290,
    badge: 'hit',
    publisher: 'Hobby World',
    year: 2000,
    designer: 'Клаус-Юрґен Вреде',
    cover: 'cover-01.svg',
    summary:
      'Класика викладання тайлів: гравці по черзі добудовують середньовічний ландшафт і виставляють підданих на дороги, міста та монастирі.',
  },
  {
    id: 'catan',
    title: 'Колонізатори',
    genre: 'strategy',
    players: [3, 4],
    time: 75,
    age: 10,
    rating: 4.8,
    reviews: 502,
    price: 1690,
    badge: 'hit',
    publisher: 'Geekach Games',
    year: 1995,
    designer: 'Клаус Тойбер',
    cover: 'cover-02.svg',
    summary:
      'Гра, з якої більшість починає знайомство з сучасними настільними іграми: видобуток ресурсів, розбудова доріг і безкінечні торги за цеглу.',
  },
  {
    id: 'wingspan',
    title: 'Крила',
    genre: 'strategy',
    players: [1, 5],
    time: 70,
    age: 10,
    rating: 4.9,
    reviews: 274,
    price: 2190,
    badge: 'new',
    publisher: 'Geekach Games',
    year: 2019,
    designer: 'Елізабет Гарґрейв',
    cover: 'cover-03.svg',
    summary:
      'Приваблюйте птахів до трьох середовищ існування й вибудовуйте ланцюжки комбінацій. Одна з найкрасивіших ігор останнього десятиліття.',
  },
  {
    id: 'terraforming-mars',
    title: 'Тераформування Марса',
    genre: 'strategy',
    players: [1, 5],
    time: 120,
    age: 12,
    rating: 4.9,
    reviews: 431,
    price: 2790,
    publisher: 'Kilogames',
    year: 2016,
    designer: 'Якоб Фрюксеніус',
    cover: 'cover-04.svg',
    summary:
      'Корпорації змагаються за перетворення Червоної планети на придатну для життя. Понад двісті карт проєктів і жодної однакової партії.',
  },
  {
    id: 'everdell',
    title: 'Еверделл',
    genre: 'strategy',
    players: [1, 4],
    time: 80,
    age: 13,
    rating: 4.8,
    reviews: 196,
    price: 2290,
    badge: 'new',
    publisher: 'Geekach Games',
    year: 2018,
    designer: 'Джеймс А. Вілсон',
    cover: 'cover-05.svg',
    summary:
      'Розміщення робітників у лісовому містечку звірят: збирайте ресурси, зводьте будівлі та встигніть до настання зими.',
  },
  {
    id: 'pandemic',
    title: 'Пандемія',
    genre: 'coop',
    players: [2, 4],
    time: 45,
    age: 8,
    rating: 4.7,
    reviews: 389,
    price: 1490,
    publisher: 'Hobby World',
    year: 2008,
    designer: 'Метт Лікок',
    cover: 'cover-06.svg',
    summary:
      'Команда фахівців гасить спалахи чотирьох вірусів по всьому світу. Або ви знайдете ліки разом, або програєте разом.',
  },
  {
    id: 'spirit-island',
    title: 'Острів Духів',
    genre: 'coop',
    players: [1, 4],
    time: 90,
    age: 13,
    rating: 4.7,
    reviews: 154,
    price: 2490,
    publisher: 'Kilogames',
    year: 2017,
    designer: 'Р. Ерік Реус',
    cover: 'cover-07.svg',
    summary:
      'Складна кооперативна стратегія, де гравці грають за духів острова й виганяють колонізаторів. Високий поріг входу, величезна глибина.',
  },
  {
    id: 'codenames',
    title: 'Кодові назви',
    genre: 'party',
    players: [2, 8],
    time: 15,
    age: 10,
    rating: 4.6,
    reviews: 612,
    price: 790,
    badge: 'hit',
    publisher: 'Ігромаг',
    year: 2015,
    designer: 'Владя Хватіл',
    cover: 'cover-08.svg',
    summary:
      'Дві команди шукають своїх агентів за асоціаціями від капітана. Правила пояснюються за хвилину, суперечки тривають годинами.',
  },
  {
    id: 'dixit',
    title: 'Діксіт',
    genre: 'party',
    players: [3, 6],
    time: 30,
    age: 8,
    rating: 4.5,
    reviews: 287,
    price: 1150,
    publisher: 'Ігромаг',
    year: 2008,
    designer: 'Жан-Луї Рубіра',
    cover: 'cover-09.svg',
    summary:
      'Гра про асоціації та сюрреалістичні ілюстрації: підкажіть так, щоб вашу картку вгадали не всі й не ніхто.',
  },
  {
    id: 'tick-tack-bumm',
    title: 'Тік Так Бум',
    genre: 'party',
    players: [2, 12],
    time: 30,
    age: 12,
    rating: 4.2,
    reviews: 143,
    price: 990,
    publisher: 'Ігромаг',
    year: 2001,
    designer: 'Петер Нойґебауер',
    cover: 'cover-10.svg',
    summary:
      'Бомба цокає, а вам треба швидко назвати слово із заданим складом. Ідеальна розминка для великої компанії.',
  },
  {
    id: 'azul',
    title: 'Азул',
    genre: 'abstract',
    players: [2, 4],
    time: 35,
    age: 8,
    rating: 4.6,
    reviews: 341,
    price: 1350,
    publisher: 'Geekach Games',
    year: 2017,
    designer: 'Міхаель Кіслінґ',
    cover: 'cover-11.svg',
    summary:
      'Приємні на дотик керамічні плитки та жорстка боротьба за викладку. Легко вчиться, складно виграється.',
  },
  {
    id: 'patchwork',
    title: 'Клаптики',
    genre: 'duel',
    players: [2, 2],
    time: 30,
    age: 8,
    rating: 4.5,
    reviews: 168,
    price: 1090,
    publisher: 'Geekach Games',
    year: 2014,
    designer: 'Уве Розенберґ',
    cover: 'cover-12.svg',
    summary:
      'Дуель про шиття ковдри з клаптиків: кожен хід — вибір між часом, ґудзиками та заповненням поля без дірок.',
  },
  {
    id: 'jaipur',
    title: 'Джайпур',
    genre: 'duel',
    players: [2, 2],
    time: 30,
    age: 10,
    rating: 4.5,
    reviews: 209,
    price: 890,
    oldPrice: 1150,
    badge: 'sale',
    publisher: 'Ігромаг',
    year: 2009,
    designer: 'Себастьян Пошон',
    cover: 'cover-13.svg',
    summary:
      'Двоє торговців змагаються за прихильність магараджі. Швидка карткова дуель про накопичення товару й вчасний продаж.',
  },
  {
    id: 'takenoko',
    title: 'Такеноко',
    genre: 'family',
    players: [2, 4],
    time: 45,
    age: 8,
    rating: 4.3,
    reviews: 122,
    price: 1590,
    publisher: 'Hobby World',
    year: 2011,
    designer: 'Антуан Боза',
    cover: 'cover-14.svg',
    summary:
      "Садівник вирощує бамбук, панда його з'їдає, а ви намагаєтеся виконати завдання швидше за суперників.",
  },
  {
    id: 'sleeping-queens',
    title: 'Сплячі королеви',
    genre: 'kids',
    players: [2, 5],
    time: 20,
    age: 6,
    rating: 4.4,
    reviews: 97,
    price: 490,
    publisher: 'Ігромаг',
    year: 2005,
    designer: 'Міранда Еванс',
    cover: 'cover-15.svg',
    summary:
      'Карткова гра, вигадана шестирічною дівчинкою: будіть королев, захищайтеся від драконів і тренуйте усний рахунок.',
  },
  {
    id: 'svyntus',
    title: 'Свинтус',
    genre: 'kids',
    players: [2, 10],
    time: 20,
    age: 5,
    rating: 4,
    reviews: 88,
    price: 390,
    oldPrice: 520,
    badge: 'sale',
    publisher: 'Hobby World',
    year: 2010,
    designer: 'Вольфґанґ Крамер',
    cover: 'cover-16.svg',
    summary:
      'Галаслива карткова гра про свинок, де правила змінюються просто посеред партії. Найкраще заходить у молодших школярів.',
  },
];
